name = "ghostb"
author = "YonV"
prefix = "ghostb"
mainprefix = "z"

[files]
include = [
    "mod.cpp",
    "README.md",
    "LICENSE",
    "3rdparty",
    "AUTHORS.txt",
    "gobp2_256_g.paa",
    "gobp2_256.paa"
]

[lint.sqf]
enabled = true # Default: true
exclude = [
    "a3/3DEN/UI/macroexecs.inc"
]

[Rapify]
exclude = [
    "a3/3DEN/UI/macroexecs.inc"
]

[asc]
enabled = true # Default: false
exclude = [
]
